 version: "3"
 services:
    jobmanager:
        image: flink
        container_name: flink-jobmanager
        expose: 
            - "6123"
        ports: 
            - "8081:8081"
        command: jobmanager
        environment: 
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
    taskmanager:
        image: flink
        container_name: flink-taskmanager
        expose: 
            - "6121"
            - "6122"
        command: taskmanager
        depends_on:
            - jobmanager
        links: 
            - "jobmanager:jobmanager"
        environment: 
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
